- alias: Notify iOS app
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SILENCE_ALARM
  condition:
    condition: state
    entity_id: input_boolean.send_push_to_martins_iphone
    state: 'on'
  action:
    service: notify.ios_martins_iphone
    data:
      message: "Testar notifiering via state på boolean"