- alias: Notify iOS app
  trigger:
    platform: state
    entity_id: device_tracker.martins_iphone
    state: 'home'
  condition:
    condition: state
    entity_id: input_boolean.send_push_to_martins_iphone
    state: 'on'
  action:
    service: notify.ios_martins_iphone
    data:
      message: "Testar notifiering via state på boolean"