- id: push_welcome_home_to_martins_ihpone
  alias: 'Välkommen hem, Martin'
  trigger:
  - entity_id: sensor.martins_iphone
    platform: state
    state: 'Online'
  condition:
  - entity_id: input_boolean.send_push_to_martins_iphone
    condition: state
    state: 'on'
  action:
  - service: notify.ios_martins_iphone
    data:
      message: "Välkommen hem"

- id: 'adjust_bedroom_light_brightness'
  alias: 'Sovrumslampa - Justera ljusstyrka'
  trigger:
  - entity_id: input_slider.bedroom_brightness
    platform: state
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.sovrum
      brightness: '{{ trigger.to_state.state | int }}'

- id: 'adjust_kitchen_light_brightness'
  alias: 'Kökslampa - Justera ljusstyrka'
  trigger:
  - entity_id: input_slider.kitchen_brightness
    platform: state
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.kok
      brightness: '{{ trigger.to_state.state | int }}'

- id: 'sync_bedroom_light_brightness_slider'
  alias: 'Sovrumslampa - Synka slider'
  trigger:
  - entity_id: light.sovrum
    platform: state
    state: 'on'
  condition:
    condition: template
    value_template: '{{ states.light.sovrum.attributes.brightness | int != states.input_slider.bedroom_brightness.state | int }}'
  action:
  - service: input_slider.select_value
    data_template:
      entity_id: input_slider.bedroom_brightness
      value: '{{ states.light.sovrum.attributes.brightness | int }}'

- id: 'sync_kitchen_light_brightness_slider'
  alias: 'Kökslampa - Synka slider'
  trigger:
  - entity_id: light.kok
    platform: state
    state: 'on'
  condition:
    condition: template
    value_template: '{{ states.light.kok.attributes.brightness | int != states.input_slider.kitchen_brightness.state | int }}'
  action:
  - service: input_slider.select_value
    data_template:
      entity_id: input_slider.kitchen_brightness
      value: '{{ states.light.kok.attributes.brightness | int }}'