default_view:
  view: yes
  name: 'Hem'
  icon: mdi:home
  entities:
    - group.weather
    - group.lights
    - group.light_brightness
    - group.steam
    - group.remote

weather:
  name: 'Väder'
  entities:
    - sensor.yr_symbol
    - sensor.yr_temperature

lights:
  name: 'Lampor'
  entities:
    - light.kok
    - light.sovrum

light_brightness:
  name: 'Ljusstyrka'
  entities:
    - input_slider.kitchen_brightness
    - input_slider.bedroom_brightness

steam:
  name: 'Steam'
  entities:
    - !secret steam_account_sensor

remote:
  name: 'Fjärrkontroll'
  entities:
    - remote.living_room