default_view:
  view: yes
  name: 'Hem'
  icon: mdi:home
  entities:
    - group.weather
    - group.lights
    - group.steam

weather:
  name: 'Väder'
  entities:
    - sensor.yr_symbol
    - sensor.yr_temperature

lights:
  name: 'Lampor'
  entities:
    - light.kok
    - light.sovrum

steam:
  name: 'Steam'
  entities:
    - !secret steam_account_sensor