default_view:
  view: yes
  name: 'Hem'
  icon: mdi:home
  entities:
    - group.weather
    - group.steam

weather:
  name: 'Väder'
  entities:
    - sensor.yr_symbol
    - sensor.yr_temperature

steam:
  name: 'Steam'
  entities:
    - !secret steam_account_sensor
